/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.BorderLayout;
import com.sun.javafx.application.PlatformImpl;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Node;
import javafx.stage.Stage;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.SwingUtilities;

/**
 *
 * @author ADMIN
 */
public class BrowserLayout extends javax.swing.JFrame {

    /**
     * Creates new form BrowserLayout
     */
    public BrowserLayout() {
        initComponents();
        initComponentWebView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mMainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected Stage mStage;
    protected WebView mWebView;
    protected JFXPanel mJFXPanel;
    protected WebEngine mWebEngine;

    protected void initComponentWebView() {
        mJFXPanel = new JFXPanel();  
        createScene(mJFXPanel);  

        mMainPanel.add(mJFXPanel, BorderLayout.CENTER);
    }
    
    protected void createScene(final JFXPanel jfxPanel) {
        PlatformImpl.startup(new Runnable() {
            @Override
            public void run() {
                mStage = new Stage();
                mStage.setTitle("Hello Java FX");
                mStage.setResizable(true);

                Group group = new Group();
                Scene scene = new Scene(group, 80, 20);
                mStage.setScene(scene);

                mWebView = new WebView();
                mWebEngine = mWebView.getEngine();
                mWebEngine.load("http://localhost/telemed");

                ObservableList<Node> children = group.getChildren();
                children.add(mWebView);

                jfxPanel.setScene(scene);
            }  
        });  
    }
    
    public static BrowserLayout CreateLayout() {
        LayoutCreator layoutCreator = new LayoutCreator();
        
        try {
            SwingUtilities.invokeAndWait(layoutCreator);
        } catch (InterruptedException ex) {
            Logger.getLogger(BrowserLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(BrowserLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return layoutCreator.getLayout();
    }
    
    protected static class LayoutCreator implements Runnable {
        protected BrowserLayout mLayout;
        
        @Override
        public void run() {
            mLayout = new BrowserLayout();
            mLayout.setVisible(true);
        }
        
        public BrowserLayout getLayout() {
            return mLayout;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mMainPanel;
    // End of variables declaration//GEN-END:variables
}
