/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author ADMIN
 */
public class IndexLayout extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public IndexLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static IndexLayout CreateLayout() {
        LayoutCreator layoutCreator = new LayoutCreator();
        
        try {
            SwingUtilities.invokeAndWait(layoutCreator);
        } catch (InterruptedException ex) {
            Logger.getLogger(IndexLayout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(IndexLayout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return layoutCreator.getLayout();
    }
    
    protected static class LayoutCreator implements Runnable {
        protected IndexLayout mLayout;
        
        @Override
        public void run() {
            mLayout = new IndexLayout();
            mLayout.setVisible(true);
        }
        
        public IndexLayout getLayout() {
            return mLayout;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
